language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: MOpc/i0Y3iT9hcdNUWQZ1iGwmp/jYiOmTlIYUk0e+Khx0hghiDNsetaBQrSYJAiagGTrw1XpQYgjy3cVf+c8ZkN+QTeca4QMw0k12v8jHSf+gw8PJnE6Nr2b/vsd7WjjVfeMxA0mLtRDZuTyGODslXrapjuXSOGH/en9NS9rCvwc7VwvYGLroYQcBzSvdpfLz01eD2YuVg6HnsGErJR9l/CSaniCPK2A9UtBdEeKQsG9xan7ab4ZfXLq4s3GzR91lIpqMjQFLX0bo5TPX7fTvPcpS4qOmybid18aM1F4rEbN+eyWYu/oOoGyCUdrhDLKmuOvh7+P5VRzk8tNxIzcEqIBH3jq1Hy8MJOtINFVHE2cNSbT59Tp9geRBY1lPtZlp83welDPlNO2oP9hiHImIgZiQBymiTCwtMLzBbDLK0Rifvcuqm4+KT5wTeEmEbnO9jJnJAaoKU5dCw4K750H51PoR+D280k4LjRD0JzD3VpcL7g/ewbtkoRKraCaTDT8d2qNV9FIhFDkNhmNopf/hB4rEvAS1FVUol4MJ5BRTwhwAYhrLFqPN/WRKf5MRh0jcSw2VJ9Cx4OTI8Zlwt1Za2AbpDiQu9USx0Zd+dDej1xsO7mdeNlUyfjuZ9CwH2NwZAKF04w7FeuVlh8MgPcXhZ3EiASk/sQ08Rh8R7qoF2A=
